# Generated by Django 3.0.6 on 2020-07-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0011_agenda_dt_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='monday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
