# Generated by Django 3.0.6 on 2020-07-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0012_funcionarios_monday'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='friday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='saturday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='sunday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='thurday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='tuesday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='wednesday',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
