# Generated by Django 3.0.6 on 2020-07-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0013_auto_20200630_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='thurday',
            new_name='thursday',
        ),
    ]
