# Generated by Django 3.0.6 on 2020-07-09 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0015_remove_funcionarios_dias_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json_Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(default=datetime.date.today)),
                ('json', models.TextField()),
            ],
        ),
    ]
