# Generated by Django 3.0.6 on 2020-07-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0016_json_agenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Json_Agenda',
        ),
    ]
