# Generated by Django 3.0.8 on 2020-07-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0017_delete_json_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='prog_tar',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
