# Generated by Django 3.0.8 on 2020-07-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0018_agenda_prog_tar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='prog_tar',
            field=models.IntegerField(default=0),
        ),
    ]
