# Generated by Django 3.0.6 on 2020-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0019_auto_20200711_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='prog_tar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
