# Generated by Django 3.0.6 on 2020-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0020_auto_20200712_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='prog_tar',
            field=models.IntegerField(default=0),
        ),
    ]
